### ISSUE TITLE
サンプルプログラムのドキュメント追加

### ISSUE THREAD

**Issue by ShotaAk** [rt-net/RaspberryPiMouse#25]
**Is your feature request related to a problem? Please describe.**
SampleProgramディレクトリのファイルに、使い方のドキュメントがない。

**Describe the solution you'd like**
READMEファイルを追加する。

**Describe alternatives you've considered**
各ファイルの冒頭に使い方を記載する。

**Comment by Tiryoh** [comment]
@ShotaAk #28 で対応できていると思うので、問題なければクローズお願いします。
