### ISSUE TITLE
Replace "Type [key]" to "Press [key]" in sample code

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/RaspberryPiMouse#30]
https://github.com/rt-net/RaspberryPiMouse/pull/28#pullrequestreview-354905438

**Comment by ShotaAk** [comment]
後ほど対応します。

**Comment by Tiryoh** [comment]
`Press [Ctrl-c] to terminate.` などの表記はREADME内のみで、サンプルプログラムの出力ではなかったため、 ドキュメントの更新のみで完結していました。 #28 がマージされたため本issueもクローズします。
