### ISSUE TITLE
セマンティックバージョニングに移行する

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/RaspberryPiMouse#36]
現状では、`1:1.4`などのようにタグのようなバージョニングをしているが、多くのカーネルモジュールでは`1.1.4`などのようにセマンティックバージョニングが採用されている。

そこで、次からバージョニングをセマンティックバージョニングにすることを提案する。
https://semver.org/

**Comment by ShotaAk** [comment]
セマンティックバージョニングに変えて良いと思います。
