### ISSUE TITLE
$ cat /dev/rtlightsensor0     error: Segmentation fault

### ISSUE THREAD

**Issue by miniberry** [rt-net/RaspberryPiMouse#7]
I can't access to the Photocoupler .
How can i deal with this problem.

thank you

**Comment by Tiryoh** [comment]
Did you turn on SPI from raspi-config?

https://www.raspberrypi.org/documentation/configuration/raspi-config.md

**Comment by miniberry** [comment]
thank you for your replay.
I use the ubuntu not raspbian. So i still need to turn on the SPI ?

**Comment by Tiryoh** [comment]
> I use the ubuntu not raspbian. So i still need to turn on the SPI ?

I understood the situation.  Yes, please enable SPI to use ` /dev/rtlightsensor0`.

**Comment by miniberry** [comment]
It works!!!
Thank you for your help^^

**Comment by Tiryoh** [comment]
I'm glad to hear that!
